public class locators {
        public static String search_bar = "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input",
                        search_button = "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input",
                        first_item = "/html/body/div[1]/div[2]/div[1]/div[1]/div/span[3]/div[2]/div[4]/div/div/div/div/div[3]/div[1]",
                        cart = "/html/body/div[1]/div[2]/div[9]/div[6]/div[1]/div[4]/div/div/div/div/form/div/div/div/div/div[3]/div/div[13]/div[1]/span/span/span/input",
                        shopping_cart_title = "/html/body/div[1]/div[2]/div[3]/div[3]/div/div[2]/div[1]/div/div/div/h1",
                        go_to_cart_button = "/html/body/div[1]/div[2]/div/div[1]/div[2]/div/div[1]/span/span",
                        check_title = "/html/body/div[1]/div[2]/div[3]/div[3]/div/div[2]/div[1]/div/form/div[2]/div[3]/div[4]/div/div[2]/ul/li[1]/span/a/span[1]/span/span[2]";
        public static String todays_deals = "/html/body/div[1]/header/div/div[4]/div[2]/div[2]/div/a[1]",
                        address = "/html/body/div[1]/header/div/div[4]/div[1]/div/div/div[3]/span[1]/span/input",
                        grocery = "/html/body/div[1]/div[21]/div/div/div/div[2]/div[2]/span[3]/span/ul/li[18]/label/input",
                        headphone = "/html/body/div[1]/div[21]/div/div/div/div[2]/div[2]/span[3]/span/ul/li[20]/label/input",
                        third_page = "/html/body/div[1]/div[21]/div/div/div/div[3]/div/ul/li[4]",
                        fourth_page = "/html/body/div[1]/div[21]/div/div/div/div[3]/div/ul/li[5]",
                        item2 = "/html/body/div[1]/div[21]/div/div/div/div[2]/div[3]/div/div[3]/div/div/a[2]/div",
                        discount = "/html/body/div[1]/div[21]/div/div/div/div[2]/div[2]/span[6]/span/ul/li[2]/div/a",
                        today_deals_title = "/html/body/div[1]/div[9]/div[1]/div/div/h1",
                        add_to_cart = "/html/body/div[1]/div[2]/div[10]/div[6]/div[1]/div[4]/div/div/div/div/form/div/div/div/div/div[3]/div/div[13]",
                        routes = "/html/body/main/section/div/div/div[1]/div/div/div/div[2]/div/div/ul/li[1]/a",
                        date = "/html/body/div[1]/table/tbody/tr[5]/td[3]/a",
                        search_bus_button = "/html/body/main/form/div[1]/div/div[2]/div[3]",
                        route_title = "/html/body/main/form/section/div/div[1]/div[1]/div[1]",
                        select_seat_button = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[1]/div[1]/div[5]/div/input[4]",
                        seat_details = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[1]/div",
                        chosse_seat = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[1]/div/div[1]/div/div/div/ul[4]/li[12]/span",
                        dropping_point = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[2]/div/div[2]/ul/li[2]/a",
                        option = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]/div/div/ul/li[1]",
                        mobile_num = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/div/div[1]/div[2]/div[1]/div/input",
                        email = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/div/div[1]/div[2]/div[2]/div/input",
                        name = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[3]/div/div/div/div/div[1]/div/div[2]/div[1]/input",
                        gender = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[3]/div/div/div/div/div[1]/div/div[2]/div[2]/select",
                        age = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[3]/div/div/div/div/div[1]/div/div[2]/div[3]/input",
                        make_payment = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[5]/div/div/div/div/div/div[2]/div[3]/input",
                        header = "/html/body/main/form",
                        consession = "/html/body/main/form/section/div/div[6]/div[3]/div[2]/div[4]/div/table/tbody/tr/td/div/div[1]/div[2]/div[3]/div/div/div/div/div[1]/div/div[2]/div[5]/select";

}
